export interface MappingEntry {
  kind: "component" | "style" | "variable";
  nodeId: string;
  linkedFile: string;
  componentName: string;
  figmaNodeName: string;
  figmaHash: string;
  codeHash: string;
  lastSyncedHash: string;
  lastSyncedAt: string;
  lastSyncSource: "figma" | "code";
  lastSyncedSnapshot?: FlatSnapshot;
  tokenSnapshot?: TokenSnapshot;
}

export interface FlatSnapshot {
  type: string;
  width: number;
  height: number;
  fills: string;
  strokes: string;
  cornerRadius: string;
  paddingTop: number;
  paddingRight: number;
  paddingBottom: number;
  paddingLeft: number;
  layoutMode: string;
  itemSpacing: number;
  childCount: number;
}

export interface VariableSnapshotEntry {
  id: string;
  name: string;
  resolvedType: "COLOR" | "FLOAT" | "STRING" | "BOOLEAN";
  collectionName: string;
  valuesByMode: Record<string, string>;
  codeSyntax?: string;
}

export interface StyleSnapshotEntry {
  id: string;
  name: string;
  styleType: "PAINT" | "TEXT" | "EFFECT";
  paints?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string;
  lineHeight?: string;
  letterSpacing?: string;
  effects?: string;
}

export type TokenSnapshot =
  | { kind: "variables"; entries: VariableSnapshotEntry[] }
  | { kind: "styles"; entries: StyleSnapshotEntry[] };

export interface GlobalConfig {
  repoOwner: string;
  repoName: string;
  branch: string;
  basePath: string;
  framework: "react" | "vue";
  styling: "tailwind" | "css-modules";
  tokenFile: string;
  componentPage?: string;
}

export type SyncState =
  | "synced"
  | "figma_changed"
  | "code_changed"
  | "conflict"
  | "newly_linked"
  | "code_only"
  | "figma_only";

// --- Component Descriptor JSON Schema ---

export interface ComponentDescriptorFill {
  type: "SOLID";
  color: string;
  opacity?: number;
  boundVariable?: string;
}

export interface ComponentDescriptorStroke {
  type: "SOLID";
  color: string;
  opacity?: number;
  weight?: number;
  align?: "INSIDE" | "OUTSIDE" | "CENTER";
  boundVariable?: string;
}

export interface ComponentDescriptorEffect {
  type: "DROP_SHADOW" | "INNER_SHADOW" | "LAYER_BLUR" | "BACKGROUND_BLUR";
  color?: string;
  offset?: { x: number; y: number };
  radius: number;
  spread?: number;
  visible?: boolean;
}

export interface ComponentDescriptorLayout {
  mode: "HORIZONTAL" | "VERTICAL" | "NONE";
  padding?: { top: number; right: number; bottom: number; left: number };
  itemSpacing?: number;
  primaryAxisAlign?: "MIN" | "CENTER" | "MAX" | "SPACE_BETWEEN";
  counterAxisAlign?: "MIN" | "CENTER" | "MAX";
  primaryAxisSizing?: "FIXED" | "AUTO";
  counterAxisSizing?: "FIXED" | "AUTO";
  boundVariables?: {
    paddingTop?: string;
    paddingRight?: string;
    paddingBottom?: string;
    paddingLeft?: string;
    itemSpacing?: string;
    counterAxisSpacing?: string;
  };
}

export interface ComponentDescriptorStyles {
  /** Reference to a local Figma PaintStyle by name (e.g. "Primary/500"). */
  fillStyleRef?: string;
  /** Reference to a local Figma PaintStyle by name for strokes. */
  strokeStyleRef?: string;
  /** Reference to a local Figma EffectStyle by name (e.g. "Elevation/Medium"). */
  effectStyleRef?: string;
  fills?: ComponentDescriptorFill[];
  strokes?: ComponentDescriptorStroke[];
  effects?: ComponentDescriptorEffect[];
  cornerRadius?: number | { topLeft: number; topRight: number; bottomLeft: number; bottomRight: number };
  width?: number;
  height?: number;
  layoutSizingHorizontal?: "FIXED" | "FILL" | "HUG";
  layoutSizingVertical?: "FIXED" | "FILL" | "HUG";
  opacity?: number;
  boundVariables?: {
    width?: string;
    height?: string;
    topLeftRadius?: string;
    topRightRadius?: string;
    bottomLeftRadius?: string;
    bottomRightRadius?: string;
    opacity?: string;
  };
}

export interface ComponentDescriptorTextStyles {
  /** Reference to a local Figma TextStyle by name (e.g. "t14"). When set,
   *  the builder binds this style instead of setting individual font props. */
  textStyleRef?: string;
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: number;
  lineHeight?: number | { value: number; unit: "PIXELS" | "PERCENT" | "AUTO" };
  letterSpacing?: number | { value: number; unit: "PIXELS" | "PERCENT" };
  textAlignHorizontal?: "LEFT" | "CENTER" | "RIGHT" | "JUSTIFIED";
  textAutoResize?: "NONE" | "WIDTH_AND_HEIGHT" | "HEIGHT" | "TRUNCATE";
  fills?: ComponentDescriptorFill[];
}

export interface ComponentDescriptorProperty {
  name: string;
  type: "VARIANT" | "BOOLEAN" | "TEXT" | "INSTANCE_SWAP";
  options?: string[];
  default: string | boolean | null;
}

export interface ComponentDescriptorChild {
  type: "FRAME" | "TEXT" | "INSTANCE" | "RECTANGLE" | "ELLIPSE" | "VECTOR" | "POLYGON" | "STAR" | "LINE";
  name: string;
  bindTo?: string;
  visibleBindTo?: string;
  componentRef?: string;
  /** Alias for componentRef — used when JSON is generated by Claude Code */
  componentName?: string;
  instanceOverrides?: Record<string, { textContent?: string }>;
  layout?: ComponentDescriptorLayout;
  styles?: ComponentDescriptorStyles;
  textStyles?: ComponentDescriptorTextStyles;
  textContent?: string;
  children?: ComponentDescriptorChild[];
  pointCount?: number;
  innerRadius?: number;
  vectorPaths?: Array<{ windingRule: "EVENODD" | "NONZERO"; data: string }>;
  rotation?: number;
}

export interface ComponentDescriptorVariantOverride {
  props: Record<string, string>;
  overrides: {
    styles?: Partial<ComponentDescriptorStyles>;
    layout?: Partial<ComponentDescriptorLayout>;
    children?: Record<string, {
      styles?: Partial<ComponentDescriptorStyles>;
      textStyles?: Partial<ComponentDescriptorTextStyles>;
      textContent?: string;
      rotation?: number;
      vectorPaths?: Array<{ windingRule: "EVENODD" | "NONZERO"; data: string }>;
    }>;
    childOrder?: string[];
    addedChildren?: ComponentDescriptorChild[];
    removedChildren?: string[];
  };
}

export interface ComponentAnnotations {
  onClick?: string;
  onChange?: string;
  onHover?: string;
  animation?: string;
  state?: string;
  a11y?: string;
  responsive?: string;
  notes?: string;
  [key: string]: string | undefined;
}

export interface ComponentDescriptor {
  $schema: string;
  name: string;
  description?: string;
  annotations?: ComponentAnnotations;
  syncNotes?: string[];
  properties?: ComponentDescriptorProperty[];
  layout?: ComponentDescriptorLayout;
  styles?: ComponentDescriptorStyles;
  children?: ComponentDescriptorChild[];
  variants?: ComponentDescriptorVariantOverride[];
}
